#!/usr/bin/env bash
make re
make test
for var in "$@"
do
	./tests_bin/ft_"$var"_test.out ./corpus_dir ./seeds -fork=5 -artifact_prefix="$var"_  -exact_artifact_path=./artifacts/$var -max_total_time=5 #2>&1 | grep ERROR -i
	norminette ../ft_$var.c
done
make fclean